baseURL = "https://sookie-id.github.io/tanya-teman"
relativeURLs = true
canonifyURLs = true
languageCode = "id-ID"
title = "Sookie Quiz"
theme = ""

[caches]
  [caches.images]
    dir = ':cacheDir/images'
